# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml
  - manifests/services.yaml
images:
  - name: PROJECT/IMAGE
    newName: rahuldesar/dummy-page-nginx:v0.1.2
