# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: dwk-environments-svc
spec:
  selector:
    app: dwk-environments
  type: LoadBalancer
  ports:
    - name: dwk-environments-svc-port
      protocol: TCP
      port: 80
      targetPort: 80
---
